server:
  port: 8093
  servlet:
    context-path: /supplier
spring:
  main: 
    allow-circular-references: true
  application:
    name: SupplierService
  datasource:
    url: jdbc:postgresql://inventory.postgres.database.azure.com:5432/Inventory-Supplier?CreateDatabaseIfNotExist=true
    username: adminroot
    password: password@123
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        namingStrategy: org.hibernate.cfg.PhysicalNamingStrategy
  cloud:
    discovery:
      enabled: false
      
swagger:
  url: https://inventory-service.test.restaurantonesolution.com/inventory
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://service-registry.test.restaurantonesolution.com/eureka
  instance:
    hostname: localhost
logging:
  level:
    '[com.ros.inventory]': DEBUG
