pipeline {
     agent any
     
        environment {
        //once you create ACR in Azure cloud, use that here
        registryName = "javaproj"
        //- update your credentials ID after creating credentials for connecting to ACR
        registryCredential = 'azcR'
        dockerImage = ''
        registryUrl = 'javaproj.azurecr.io'
    }
    
    stages {
        stage ('Build Docker image') {
            steps {
                script{
                dockerImage = docker.build registryName + ":${BUILD_NUMBER}"
                }
                 
            }
        }
         stage('Upload Image to ACR') {
     steps{   
         script {
            docker.withRegistry( "http://${registryUrl}", registryCredential ) {
            dockerImage.push()
            }
        }
      }
    }
}
}
